#!/bin/sh
set -eu

export RUSTUP_TOOLCHAIN=nightly-2026-05-28
export CARGO_UNSTABLE_BUILD_STD=panic_abort,std
export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--shared-memory -C link-arg=--max-memory=1073741824 -C link-arg=--import-memory -C link-arg=--export=__wasm_init_tls -C link-arg=--export=__tls_size -C link-arg=--export=__tls_align -C link-arg=--export=__tls_base'
export TRUNK_BUILD_FEATURES=browser-threads

exec trunk "$@"
